<a href="https://colab.research.google.com/github/fa4401764-cpu/Rohmix_Technologies_tasks/blob/main/Rohmbix__Technologies__Task_1%5Bproject_01%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data:pd.DataFrame=pd.read_csv(r"C:\Users\fa440\Downloads\csv files\Loan_prediction_default.csv")

In [ ]:
data.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

In [ ]:
data = data.drop_duplicates()

In [ ]:
data.isnull().sum      # Handling missing values in a Data frame

<bound method DataFrame.sum of         LoanID    Age  Income  LoanAmount  CreditScore  MonthsEmployed  \
0        False  False   False       False        False           False
1        False  False   False       False        False           False
2        False  False   False       False        False           False
3        False  False   False       False        False           False
4        False  False   False       False        False           False
...        ...    ...     ...         ...          ...             ...
255342   False  False   False       False        False           False
255343   False  False   False       False        False           False
255344   False  False   False       False        False           False
255345   False  False   False       False        False           False
255346   False  False   False       False        False           False

        NumCreditLines  InterestRate  LoanTerm  DTIRatio  Education  \
0                False         False     False     False      False
1                False         False     False     False      False
2                False         False     False     False      False
3                False         False     False     False      False
4                False         False     False     False      False
...                ...           ...       ...       ...        ...
255342           False         False     False     False      False
255343           False         False     False     False      False
255344           False         False     False     False      False
255345           False         False     False     False      False
255346           False         False     False     False      False

        EmploymentType  MaritalStatus  HasMortgage  HasDependents  \
0                False          False        False          False
1                False          False        False          False
2                False          False        False          False
3                False          False        False          False
4                False          False        False          False
...                ...            ...          ...            ...
255342           False          False        False          False
255343           False          False        False          False
255344           False          False        False          False
255345           False          False        False          False
255346           False          False        False          False

        LoanPurpose  HasCoSigner  Default
0             False        False    False
1             False        False    False
2             False        False    False
3             False        False    False
4             False        False    False
...             ...          ...      ...
255342        False        False    False
255343        False        False    False
255344        False        False    False
255345        False        False    False
255346        False        False    False

[255347 rows x 18 columns]>

In [ ]:
data.dropna()   # drop missing values

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255342,8C6S86ESGC,19,37979,210682,541,109,4,14.11,12,0.85,Bachelor's,Full-time,Married,No,No,Other,No,0
255343,98R4KDHNND,32,51953,189899,511,14,2,11.55,24,0.21,High School,Part-time,Divorced,No,No,Home,No,1
255344,XQK1UUUNGP,56,84820,208294,597,70,3,5.29,60,0.50,High School,Self-employed,Married,Yes,Yes,Auto,Yes,0
255345,JAO28CPL4H,42,85109,60575,809,40,1,20.90,48,0.44,High School,Part-time,Single,Yes,Yes,Other,No,0
255346,ZTH91CGL0B,62,22418,18481,636,113,2,6.73,12,0.48,Bachelor's,Unemployed,Divorced,Yes,No,Education,Yes,0

In [ ]:
data.columns = data.columns.str.strip()

In [ ]:
data.describe()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Default
count,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000
mean,43.498306,82499.304597,127578.865512,574.264346,59.541976,2.501036,13.492773,36.025894,0.500212,0.116128
std,14.990258,38963.013729,70840.706142,158.903867,34.643376,1.117018,6.636443,16.969330,0.230917,0.320379
min,18.000000,15000.000000,5000.000000,300.000000,0.000000,1.000000,2.000000,12.000000,0.100000,0.000000
25%,31.000000,48825.500000,66156.000000,437.000000,30.000000,2.000000,7.770000,24.000000,0.300000,0.000000
50%,43.000000,82466.000000,127556.000000,574.000000,60.000000,2.000000,13.460000,36.000000,0.500000,0.000000
75%,56.000000,116219.000000,188985.000000,712.000000,90.000000,3.000000,19.250000,48.000000,0.700000,0.000000
max,69.000000,149999.000000,249999.000000,849.000000,119.000000,4.000000,25.000000,60.000000,0.900000,1.000000

In [ ]:
data.to_csv("cleaned_loan_prediction_data.csv", index=False)   # IMPORT CLEANED DATASET

In [ ]:
import os
os.listdir()

['.idea',
 '.venv',
 'cleaned_loan_prediction_data.csv',
 'data',
 'models',
 'README.md',
 'Rohmbix _Technologies _Task_1[project 01].ipynb',
 'Rohmbix _Technologies _Task_1[project 02].ipynb',
 'sample.ipynb']

In [ ]:
data.shape

(255347, 18)

In [ ]:
data.describe()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Default
count,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000
mean,43.498306,82499.304597,127578.865512,574.264346,59.541976,2.501036,13.492773,36.025894,0.500212,0.116128
std,14.990258,38963.013729,70840.706142,158.903867,34.643376,1.117018,6.636443,16.969330,0.230917,0.320379
min,18.000000,15000.000000,5000.000000,300.000000,0.000000,1.000000,2.000000,12.000000,0.100000,0.000000
25%,31.000000,48825.500000,66156.000000,437.000000,30.000000,2.000000,7.770000,24.000000,0.300000,0.000000
50%,43.000000,82466.000000,127556.000000,574.000000,60.000000,2.000000,13.460000,36.000000,0.500000,0.000000
75%,56.000000,116219.000000,188985.000000,712.000000,90.000000,3.000000,19.250000,48.000000,0.700000,0.000000
max,69.000000,149999.000000,249999.000000,849.000000,119.000000,4.000000,25.000000,60.000000,0.900000,1.000000